name: Tester

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Test and Coverage
        run: yarn test --coverage --silent